### PR TITLE
Frontend/forget password

### PR DESCRIPTION
**Pull request by gokayyildiz**
Implementation for forget password page and its link with other pages implemented. After the merge of this branch we can continue with the backend connection of the given application

### CODE REVIEW

**Comment by Koraytkn** [comment]
If you don't merge the frontend/dev (version after merging the current phase of the Login page) to your forget-password branch in your local and update the Login/ Sign In conversion specific parts, we will need to create two additional branches instead of one(I will also need to change the forgot password navigation link in Login page). Is this update possible for you?

**Comment by Koraytkn** [comment]
Screen Shot 2022-10-27 at 23 36 18
This button label for example or the navigation link underneath it

**Comment by gokayyildiz** [comment]
Actually I changed the page that you send in the review, maybe you can try with a git pull and run again or I made a mistake while uploading

**Review by xltvy — CHANGES_REQUESTED** [review]
Nice work @gokayyildiz, one little thing:
Ekran Resmi 2022-10-28 23 41 51
I have marked a space in this screenshot. I think if the start of each line in each text area is aligned it will look more clean. So, password is standing a bit odd here. Other than that, I see no problem for the initial structure and layout of the page.

**Comment by gokayyildiz** [comment]
review requests are fixed can be merged

**Comment by xltvy** [comment]
It seems okay now, merging.

**Pull request merged**
