### PR TITLE
Mobile/verification screen 395

### LINKED ISSUE #395: Mobile: Implementing Verification Screen
### Issue Description

As we decided on our [first mobile team meeting](https://github.com/bounswe/bounswe2022group2/wiki/Mobile-Team-Meeting-1-for-451-(17.10.2022)), I have to implement Verification screen of our mobile application.

### Step Details

Steps that will be performed:
- [x] Initialize verification screen
- [x] Add necessary widgets: confirm button, verification code insert fields, etc.
- [x] Add logo, title, etc. miscellaneous components
- [x] Set up proper navigation routes

### Final Actions

After I complete all steps mentioned above, I will test my code on an emulator. If it works as we wish, I will open a pull request to merge my code with the existing code for mobile part of our application.

### Deadline of the Issue

27.10.2022 - Thursday - 23:59

### Reviewer

Ezgi Aysel Batı

### Deadline for the Review

28.10.2022 - Friday - 23:59

### PR DESCRIPTION
**Pull request by egemenatikk**
I finished implementing verification screen, it does not include backend connections yet.

I added: 
* Logo of our application
* Title of screen
* Description of functionality
* Verification code entering field
* "Request another code" button
* Remaining time information
* Verify button
* "Change the email" button

Closes #395

### CODE REVIEW

**Comment by egemenatikk** [comment]
I updated "change email" button as "back to previous page" button

**Review by bahricanyesil — CHANGES_REQUESTED** [review]
You can add the email of the user (taken from the signup page) under the "verify your email" title or you can add the email under the "please enter the verification code ..." text to indicate the email address of the user verification code is sent.

**Review by bahricanyesil — CHANGES_REQUESTED** [review]
When the time is up, the action button should be deactivated. The user shouldn't be able to click the verify button since the time is up and the code is invalid. (User has to click the "request another code" text.)

**Comment by egemenatikk** [comment]
> You can add the email of the user (taken from the signup page) under the "verify your email" title or you can add the email under the "please enter the verification code ..." text to indicate the email address of the user verification code is sent.

> When the time is up, the action button should be deactivated. The user shouldn't be able to click the verify button since the time is up and the code is invalid. (User has to click the "request another code" text.)

I updated my implementation as you suggested.

**Review by bahricanyesil — APPROVED** [review]

**Comment by bahricanyesil** [comment]
Thank you for the changes.

**Pull request merged**
