### PR TITLE
implementation of NavBar

### LINKED ISSUE #533: Frontend: Static Navigation Bar
### Issue Description

As stated in the outcome of the second front-end team [meeting](https://github.com/bounswe/bounswe2022group2/wiki/Meeting-%232-of-the-Frontend-Team) for the pages not related to authentication there should be a static navigation bar to ease the surf of the users; which consists of the "Learnify" logo, a search bar(implementation of the search bar will be conducted later), notifications button, Home button, Catagories button, About button, Contact button, and Profile Page button. 

### Step Details

Steps that will be performed:
- [x] Examine the mock home-page design 
- [x] Decide on the components (some of which are active)
- [x] Implementation of the items and visual inspection on a sample page. 

### Final Actions

A related branch will be used during the implementation and inspection, then a Pull Request will be created.

### Deadline of the Issue

08.11.2022 - 23.59

### Reviewer

Mehmet Gökay Yıldız

### Deadline for the Review

08.11.2022 - 23.59

### PR DESCRIPTION
**Pull request by Koraytkn**
## Short Description

Static NavBar implemented, further information can be seen at the related [issue](https://github.com/bounswe/bounswe2022group2/issues/533) 

------

## What Does This PR Include?

1. Implementation of the NavBar

------

Closes #533

### CODE REVIEW

**Review by xltvy — CHANGES_REQUESTED** [review]
Thank you for your work. Besides some small things I think it is complete. Here are the things I would like to mention (I have also uploaded a screenshot of the navbar live from my local):

1. When you put mouse cursor on a navbar field, it changes to a blueish background. In the screenshot the mouse cursor is on Home for instance. We may change it to only clickable cursor, not anything else (background etc.)
2. You have mistakenly written "Catagories" instead of "Categories"
3. The color of each list item in the NavBar is not the the dark blue color of our app's color scheme. Instead of using `color: rgb(29, 7, 228);` in the color declaration in the appropriate css class, we may use `color: #1746A2;`
4. In the NavBar.js every list item directs to /home-page, we may change them to their respective extensions (/categories for Categories etc.)
5. In my home page implementation I have changed the home page's extension as /home, you may also change it beforehand
6. I am not sure that the font is open sans for the NavBar list items, we may add a className for each item and then in the css file, add their font as `font-family: 'Open Sans' sans-serif;`
7. Although it would not function yet, I think implementing an input accepting search bar would be nice for the upcoming weeks (the weeks that are closer to the milestone), instead of writing only search bar.
8. And last, we may change the bell icon with the svg file that I have sent you. Because using svg files are way better for the performance.
Ekran Resmi 2022-11-08 22 18 29

**Comment by xltvy** [comment]
I have also realized that the cream background of the navbar is not the cream color code of our color scheme.

Instead of writing `background-color: #f3e1d2;` we may use `background-color: #FFF7E9;`

**Comment by Koraytkn** [comment]
1. Done
2. Resolved
3. I have changed to the right "blue".
4. I have changed the extensions.
5. Also updated in the NavBar implementation 
6. Added the font type.
7. Done (Doesn't look good nor function)
8. Talked about this in the front-end team meeting4, will be changed later.
9. Changed the background color for the Navigation bar.

    Now I am committing the latest version, thanks for this valuable feedback.

**Comment by Koraytkn** [comment]
Screen Shot 2022-11-09 at 22 42 52

This is the latest versions snapshot.

**Review by xltvy — APPROVED** [review]
Approving

**Pull request merged**
