### PR TITLE
Backend: Implementing Unit Tests for Login endpoint

### PR DESCRIPTION
**Pull request by codingAku**
This PR is related to #421 and closes it. Unit tests for login endpoint has been implemented.
This PR includes:

1- Unvalid request body check
2- Wrong password check
3- Non-existent email check
4- Login for valid user.

### CODE REVIEW

**Comment by mbatuhancelik** [comment]
I believe the success: 200 case should mock the JWT library to see if the endpoint really returns the jwt token generated by the jwt library or some random token.

**Comment by codingAku** [comment]
> 

Hello, does it suppose to create a token with user info 

> I believe the success: 200 case should mock the JWT library to see if the endpoint really returns the jwt token generated by the jwt library or some random token.

Hello, Do I need to check if it's the same token I have created with user id and email? Because, the token I generate in test file with user email and id is not the same with response token, although approx. first 30 characters are the same?

**Comment by mbatuhancelik** [comment]
> > 
> 
> Hello, does it suppose to create a token with user info
> 
> > I believe the success: 200 case should mock the JWT library to see if the endpoint really returns the jwt token generated by the jwt library or some random token.
> 
> Hello, Do I need to check if it's the same token I have created with user id and email? Because, the token I generate in test file with user email and id is not the same with response token, although approx. first 30 characters are the same?

Its natural they diverge at some point, the part of the JWT encoding username will be same but I believe JWT also contains a timestamp, so only the code generated in the same UTC time will be the same.

**Comment by mbatuhancelik** [comment]
Current version certainly checks if the right jwt token is returned! 
Approved

**Review by mbatuhancelik — APPROVED** [review]

**Pull request merged**
