### PR TITLE
Mobile: My Profile Screen Update

### LINKED ISSUE #775: Mobile: Updating My Profile Page
### Issue Description

I will update the my user page that can be accessed by fourth section of the navigation bar. 

### Step Details

Steps that will be performed:
- [x] Add biography to the profile page
- [x] Make this section editable
- [x] Add my courses section

### Final Actions

When the final page is done, I will provide a record of the screen here to be reviewed.

### Deadline of the Issue

22.12.2022 - 23.59

### PR DESCRIPTION
**Pull request by onurkomurcu**
## Short Description

I have updated the profile screen. In the lab session, according to our TA's response, we are not going to delete static widgets. Due to that situation, I didn't  delete the contribution graph. Also I didn't delete the total count row which includes number of friends, enrolled learning spaces and contributions. Among these numbers, only number of enrolled learning spaces is true. Other than that, number of friends is initialized 0 always. Number of contribution is assumed equal to the number of enrolled learning spaces.  

------

## What Does This PR Include?

1. Added biography field
2. Added view all enrolled learning spaces button
3. Updated totalCountRow widget 
4. Updated profile screen tests

------

Closes #775

### CODE REVIEW

**Comment by onurkomurcu** [comment]
https://user-images.githubusercontent.com/92719802/209022672-6fcc9c11-3b26-4ea2-817a-799d2dba55fe.mov

**Comment by ezgy** [comment]
I think you should either update the unit tests to fit these changes or remove the invalid ones until you write new tests, otherwise, if we merge this the checks will fail for all the following work.

**Comment by onurkomurcu** [comment]
I

> I think you should either update the unit tests to fit these changes or remove the invalid ones until you write new tests, otherwise, if we merge this the checks will fail for all the following work.

I updated the profile page tests. Now, it is ready to be merged.

**Comment by bahricanyesil** [comment]
I have reviewed your work:

1- I think we need to remove "friends" number (or maybe remain idk)
2- "enrolled" number is not correct, you should update it also
3- "contributed" number is not correct, you can write the number of ls created by the user (you may think to change the text as "created")
4- The graph has not any meaningful data right now, will it stay?

**Review by bahricanyesil — CHANGES_REQUESTED** [review]
I have reviewed your work:

Here're my questions and change requests:
1- I think we need to remove "friends" number (or maybe remain idk)
2- "enrolled" number is not correct, you should update it also
3- "contributed" number is not correct, you can write the number of ls created by the user (you may think to change the text as "created")
4- The graph has not any meaningful data right now, will it stay?

**Comment by onurkomurcu** [comment]
> 1- I think we need to remove "friends" number (or maybe remain idk) 
> 4- The graph has not any meaningful data right now, will it stay? 

As we discussed in the lab session, even if widget is non-functional & static, it can be stay. If we decide to remove all static widgets across platform, we will also delete friends number and graph. However, in my opinion, it can be stay for now. 

> 2- "enrolled" number is not correct, you should update it also 

It is because backend connection is not implemented. 

3- "contributed" number is not correct, you can write the number of ls created by the user (you may think to change the text as "created") 

Endpoint returns two learning space list: enrolled and created learning spaces. When I open this PR, created learning spaces was not known to be received. I will add another button for looking up created learning spaces. Also, number of contributed learning spaces can be replaced with number of created learning spaces. 

> 5- You should fetch all data on these page from the back-end with the corresponding endpoint, you may think to do this on another branch but do not forget.

Of course, @bahricanyesil :)

I am going to add another button for looking created learning spaces. Other than that, correctness of the data is provided when the endpoint connection is implemented. Thank you for your review, @bahricanyesil.

**Comment by onurkomurcu** [comment]
Screenshot_1671965785

**Review by egemenatikk — APPROVED** [review]

**Review by bahricanyesil — APPROVED** [review]
Thanks for your work and informing.

**Pull request merged**
