### PR TITLE
adding  AWS, Docker, Gmail and NodeJS to tools evaluation

### PR DESCRIPTION
**Pull request by mbatuhancelik**
I investigated technologies mentioned above in our tools evaluation section.

### CODE REVIEW

**Review by bahricanyesil — APPROVED** [review]
I've read the texts you wrote. Good work, eline sağlık!

**Review by bahricanyesil — CHANGES_REQUESTED** [review]
Please start the enumeration from 5 since Flutter is the forth item.

**Comment by mbatuhancelik** [comment]
There is something wrong with me nowadays.
Done

**Review by bahricanyesil — APPROVED** [review]
Thanks for the change!

**Pull request merged**
