### PR TITLE
Frontend: Sign up page implementation

### PR DESCRIPTION
**Pull request by xltvy**
Sign up page is implemented and customized according to the style of our web application. No backend connection is established.

### CODE REVIEW

**Comment by gokayyildiz** [comment]
seems like a good design for sign up page, we should follow this pattern for other authentication related pages

**Review by gokayyildiz — APPROVED** [review]
works nicely

**Comment by surmelienes1** [comment]
Thank you @xltvy for your detailed work! This design will be a great basis for the rest of the frontend development.

**Review by surmelienes1 — APPROVED** [review]
Thank you @xltvy for your detailed work! This design will be a great basis for the rest of the frontend development.

**Pull request merged**
