### PR TITLE
Evaluation of Tools, Processes and individual work

### LINKED ISSUE #496: Milestone 1: Evaluation of Tools and Processes
### Issue Description

As decided in our general team meeting the part related to the tools we have selected to use during the development of our project and the processes we are going through will be specified by @bahricanyesil, @mbatuhancelik, and me for the group review part of Milestone 1. We have selected one person from each sub-group to emphasize the technologies used by different subgroups better. This issue is related to the parts that I will be writing. 

### Step Details

Steps that will be performed:
- [x] Writing the parts that are my responsibility (React). 
- [x] Creating the parts related to the Evaluation of the process (Team Meetings, TA Meetings, Issue Creation and Management.)

### Final Actions

A PR will be created and merged with the master. 

### Deadline of the Issue

04.11.2022 - 18.59

### Reviewer

Muhammed Enes Sürmeli

### Deadline for the Review

04.11.2022 - 22.59

### PR DESCRIPTION
**Pull request by Koraytkn**
I have created the evaluation of processes part, and added a team meetings section; for the evaluation of the tools React related part has been added.

Closes #496

### CODE REVIEW

**Review by mbatuhancelik — COMMENTED** [review]
This is an older version of Master.
Please be careful to not to erase anything during the merge, also enumeration should change too.

**Review by mbatuhancelik — APPROVED** [review]

**Review by mbatuhancelik — CHANGES_REQUESTED** [review]
We need to merge Master into this branch before merging.
I tought Github user interface would allow us to resolve conflicts, but it just erases the part I wrote :/

**Review by mbatuhancelik — APPROVED** [review]

**Review by bahricanyesil — CHANGES_REQUESTED** [review]
Can you also please add "TA/Customer Meetings" and "Issue Creation and Management" sections?

**Review by bahricanyesil — APPROVED** [review]
Thanks for the additions, I couldn't see any further problem.

**Comment by egemenatikk** [comment]
> Thanks for the additions, I couldn't see any further problem.

There were merge conflicts, I resolved them and your approval is cancelled automatically, I guess. Can you approve again, @bahricanyesil ?

**Review by bahricanyesil — APPROVED** [review]
LGTM!

**Pull request merged**
