### PR TITLE
Practice app/frontend/categories page 204

### PR DESCRIPTION
**Pull request by mbatuhancelik**
As mentioned in #204, frontend page for categories is implemented and ready to be used.

### CODE REVIEW

**Comment by xltvy** [comment]
After running the code in my local, I have observed that when entering an invalid category in Add Category field, the category is added as undefined. I think it should show an error and do not add anything to the categories list.

Besides that I think everything looks amazing, good work!

**Review by xltvy — COMMENTED** [review]
After running the code in my local, I have observed that when entering an invalid category in Add Category field, the category is added as undefined. I think it should show an error and do not add anything to the categories list.

Besides that I think everything looks amazing, good work!

**Comment by mbatuhancelik** [comment]
I solved the problem and added suggesting feature property to the categories.
I believe it is ready for another review now.

**Review by bahricanyesil — APPROVED** [review]
I reviewed the whole work you did. I fetched and pulled the branch on my local repo. Then, I tested the functionalities. I encountered with the error about two way suggestions (suggesting sport when written sports and vice versa). @mbatuhancelik solved this problem with the latest commit. Currently, I couldn't see anyother problem and the functionality works as expected. I am approving the PR and merging it to the master branch.

**Pull request merged**
