### PR TITLE
Implement the get lesson by category endpoint - 159

### LINKED ISSUE #159: Practice App: Implement the Get Lesson By Category Endpoint
### Issue Description

We determined the endpoints to be included in the practice app project in our [weekly meeting-9](https://github.com/bounswe/bounswe2022group2/wiki/Meeting-%239-(01.05.2022)).

After the determination of the complete list, we divided the tasks within the team. I took the responsibility for the get lesson by category endpoint.

### Step Details

Steps that will be performed:
- [x] Check whether the incoming data is valid
- [x] Return the lessons with the given category
- [x] Return an error message if an error occurs in any of the previous steps
- [x] Test the endpoint with Postman
- [x] Save requests as a collection in Postman
- [x] Document the endpoint

### Final Actions

After I created the get lesson by category endpoint, I will test it by using Postman. While testing, I will save my successful and failed requests and I will create a collection in Postman. I will also give the link to the collection under this as a comment to enable anyone to test the endpoint. Finally, I will document the endpoint and will share the documentation as a comment under this issue to add it to the corresponding wiki page in the future.

### Deadline of the Issue

08.05.2022 - Sunday - 23:59

### Reviewer

Altay Acar

### Deadline for the Review

09.05.2022 - Monday - 23:59

### PR DESCRIPTION
**Pull request by bahricanyesil**
This PR includes the following actions:

1. Check whether the incoming data is valid
2. Return the lessons with the given category
3. Return an error message if an error occurs in any of the previous steps
4. Test the endpoint with Postman
5. Save requests as a collection in Postman
6. Document the endpoint

Now, the get lessons by category endpoint is ready for requests.

This PR closes #159, other details can also be seen from that issue.

### CODE REVIEW

**Review by xltvy — APPROVED** [review]
I have reviewed your work on getting lessons by category and I think it seems very detailed and good if not perfect. So, I am approving your request. Good work!🎉

**Review by xltvy — APPROVED** [review]
Approved.

**Comment by bahricanyesil** [comment]
## Example Requests and Responses

**1. 400 Bad Request - Invalid Body - Invalid category id**
Screen Shot 2022-05-19 at 08 49 52

---
 
**2. 200 OK - Success Message**
Screen Shot 2022-05-19 at 08 49 17

**Comment by bahricanyesil** [comment]
## Postman Documentation

Here's the screenshot of the postman documentation:
Screen Shot 2022-05-19 at 08 54 58


[Postman Documentation Link](https://documenter.getpostman.com/view/12694000/Uyxbq9MC)

**Pull request merged**
