### PR TITLE
Milestone 2: Merge dev to master

### PR DESCRIPTION
**Pull request by mbatuhancelik**
As the milestone 2 has come, we need to create a release, thus, we should merge our development to the master now.
Thanks everyone for the hard work.

### CODE REVIEW

**Review by xltvy — DISMISSED** [review]
Here is my review:

🧿

**Review by gokayyildiz — APPROVED** [review]
Superb effort by the team, thank you for all the efforts made and time spent whole team!

**Review by codingAku — APPROVED** [review]
Excited for release. Approved.

**Review by surmelienes1 — APPROVED** [review]
Thank you everyone for their valuable contributions! We have made a great job working collaboratively!

**Review by bahricanyesil — APPROVED** [review]
Thank you all for your hardwork 💪🏻✨

**Pull request merged**
