### PR TITLE
Mobile: Multi Theme Support - Settings

### LINKED ISSUE #763: Mobile: Multi-Theme Support and Settings
### Issue Description

I created a settings screen in the app with issue #758. The settings screen has a theme section to allow users to switch between dark and light modes. As you know, dark modes are so popular these days. Therefore, we wanted to support dark mode in our app to attract users and also make it easier to use the app at midnight. Our app was only supporting the light mode previously. With this issue, I will implement the theme section of the settings part. I will modify the light/dark mode colors. Finally, I will make the necessary modifications in the theme provider to allow users to switch between light/dark themes and listen to these changes across the app. Users' last theme preference will also be stored locally to remember.

### Step Details

Steps that will be performed:
- [x] Support dark and light themes
- [x] Implement get and set methods for themes (from and to local storage)
- [x] Implement dark mode text under the theme section of the settings screen
- [x] Integrate theme switch
- [x] Fix learning space detail screen color
- [x] Fix text item dark mode color
- [x] Fix profile chart text colors
- [x] Fix the GitHub icon color in the social accounts section

### Final Actions

I will test the implementation and widgets created on my real phone. If everything works, I will open a pull request. If the pull request is approved by at least one teammate, I will merge it and close the issue.

### Deadline of the Issue

21.12.2022 - Wednesday [23.59]

### Reviewer

Onur Kömürcü

### Deadline for the Review

22.12.2022 - Thursday [23.59]

### PR DESCRIPTION
**Pull request by bahricanyesil**
## Short Description

With this PR, multi-theme support will be added to the app with the light and dark mode options. Some detected color issues in the dark mode will also be handled. In the end, users will be able to switch between light and dark modes in the settings screen.

------

## What Does This PR Include?

1. Support dark and light themes
2. Implement get and set methods for themes (from and to local storage)
3. Implement dark mode text under the theme section of the settings screen
4. Integrate theme switch
5. Fix learning space detail screen color
6. Fix text item dark mode color
7. Fix profile chart text colors
8. Fix the GitHub icon color in the social accounts section

------

Closes #763

### CODE REVIEW

**Comment by bahricanyesil** [comment]
Here's a video recording from the app which demonstrates the full functionality and effect of the multi-theme support:

https://user-images.githubusercontent.com/60237280/208294464-94b0e99e-a8c4-4268-92b0-d478b7069300.mp4

**Comment by bahricanyesil** [comment]
Here's a screenshot from the app with the theme switch when the dark mode is on:

Screen Shot 2022-12-18 at 13 43 39

**Comment by bahricanyesil** [comment]
Here's a screenshot from the app with the theme switch when the dark mode is off:

Screen Shot 2022-12-18 at 13 42 56

**Review by onurkomurcu — APPROVED** [review]
Night owls will love this feature absolutely :). Thank you for your exclusive work, @bahricanyesil !

**Pull request merged**
