### PR TITLE
Create practice app folder, gitignore and readme files

### PR DESCRIPTION
**Pull request by bahricanyesil**
As a part of our main issue (#143) for the initialization of the practice app project, I took the responsibility for some items and performed the required actions.

This pull request contains the following developments:
1. Created "practice-app" folder under the main repository folder
2. Created a base gitignore file for Django

With the work included in this pull request, I, personally, experienced the "commit", "push", "pull request", "merge", and some other notions/commands/actions that we should learn.

### CODE REVIEW

**Comment by bahricanyesil** [comment]
I will be adding some additional content to the gitignore file about the files that should be ignored regardless of the programming language/framework used (such as specific files for macOS developers).

**Comment by bahricanyesil** [comment]
## Info

I updated the .gitignore file with additional lines related to macOS and vscode specific files.

**Comment by bahricanyesil** [comment]
It is ready to be reviewed by @onurkomurcu.

**Review by onurkomurcu — APPROVED** [review]
It seems adequate for now, @bahricanyesil. Thank you for your work.

**Pull request merged**
