### PR TITLE
Dev to Master

### PR DESCRIPTION
**Pull request by gokayyildiz**
To create a release for Milestone 1.

### CODE REVIEW

**Comment by Koraytkn** [comment]
As the front-end team, we have completed the development process for the first milestone, and merged the frontend/dev branch to the Dev branch right after the deployment of the web application to AWS. In terms of the web application and the front-end team merging to Master has no inconvenience.

**Review by Koraytkn — APPROVED** [review]
The web-application is ready to be merged into the Master branch.

**Comment by bahricanyesil** [comment]
The mobile app is also ready for merge and release.

**Review by bahricanyesil — APPROVED** [review]
We are ready for our demo app and also the first release

**Pull request merged**
