### PR TITLE
Implement the drop lesson endpoint

### LINKED ISSUE #174: Practice App: Implementing the POST method for dropping lesson, lesson drop endpoint
### Issue Description

We determined the endpoints to be included in the practice app project in our [weekly meeting-9](https://github.com/bounswe/bounswe2022group2/wiki/Meeting-%239-(01.05.2022)).

After the determination of the complete list, we divided the tasks within the team. I took the responsibility for the implementation of a POST method for dropping lesson. To be able to implement the signup endpoint, we need User and Lesson models.

### Step Details

Steps that will be performed:
- [x] Check whether the incoming data is valid
- [x] Check whether the user and lesson exists
- [x] Check whether the user takes the lesson
- [x] Remove the lesson from user's enrollment list and return the user and lesson with a success message
- [x] Return an error message if an error occurs in any of the previous steps
- [x] Test the endpoint with Postman
- [x] Save requests as a collection in Postman
- [x] Document the endpoint

### Final Actions

After I created the drop lesson endpoint, I will test it by using Postman. While testing, I will save my successful and failed requests and I will create a collection in Postman. I will also give the link to the collection under this as a comment to enable anyone to test the endpoint. Finally, I will document the endpoint and will share the documentation as a comment under this issue to add it to the corresponding wiki page in the future.

### Deadline of the Issue

15.05.2022 - Sunday - 23:59

### Reviewer

Mehmet Batuhan Çelik

### Deadline for the Review

16.05.2022 - Monday - 23:59

### PR DESCRIPTION
**Pull request by egemenatikk**
This PR includes the following actions:

1. Check whether the incoming data is valid or not
2. Check whether a user with the given user_id and a lesson with the given lesson_id exists or not.
3. Check whether the user with the given user_id takes the lesson with the given lesson_id or not.
4. Remove the lesson from user's enrollment list and return the user and lesson with a success message
5. Return an error message if an error occurs in any of the previous steps
6. Test the endpoint with Postman
7. Save requests as a collection in Postman
8. Document the endpoint

Now, the drop lesson endpoint is ready for requests.

This PR closes #174 , other details can also be seen from that issue.

### CODE REVIEW

**Review by mbatuhancelik — CHANGES_REQUESTED** [review]
Firstly, please use a joi validator to check if the request body has the required fields. 

Secondly, you may had made some extensive testing. Instead of checking if the given ids exists in mongoose and then fetching documents by ids, you could directly try to fetch objects and return 400 if you could not get an user and lesson. Thus, you may decrease the number of database interactions. 

The latter is just a suggestion and it is fine as it is since with this project we do not expect a huge traffic, whereas, please use Joi for validation for the sake of following convention.

**Comment by egemenatikk** [comment]
> Firstly, please use a joi validator to check if the request body has the required fields.
> 
> Secondly, you may had made some extensive testing. Instead of checking if the given ids exists in mongoose and then fetching documents by ids, you could directly try to fetch objects and return 400 if you could not get an user and lesson. Thus, you may decrease the number of database interactions.
> 
> The latter is just a suggestion and it is fine as it is since with this project we do not expect a huge traffic, whereas, please use Joi for validation for the sake of following convention.

I added a Joi validator as you suggested, can you check if everything is okay?

**Review by mbatuhancelik — APPROVED** [review]
LGTM!

**Comment by egemenatikk** [comment]
> Firstly, please use a joi validator to check if the request body has the required fields.
> 
> Secondly, you may had made some extensive testing. Instead of checking if the given ids exists in mongoose and then fetching documents by ids, you could directly try to fetch objects and return 400 if you could not get an user and lesson. Thus, you may decrease the number of database interactions.
> 
> The latter is just a suggestion and it is fine as it is since with this project we do not expect a huge traffic, whereas, please use Joi for validation for the sake of following convention.

I also implemented the second suggestion you made, if you think it would be better that way, I can change it.

**Pull request merged**
