### PR TITLE
Dev frontend update profile

### LINKED ISSUE #856: Frontend: Profile page design, renaming and components refinement.
### Issue Description

Since we have worked with @gokayyildiz through the implementation of the profile page and the components within the layout of the profile page have been outdated slightly and need to be revised; also the naming and the CSS components of some components need to be changed for better UX. This is a sub-issue under the profile page implementation [issue](https://github.com/bounswe/bounswe2022group2/issues/771)

### Step Details

Steps that will be performed:
- [x] Fetch and pull the latest version of the Profile Page development branch.
- [x] Create the related branch for this sub-issue.
- [x] Decide on the changes and reshapings/renamings that need to be done.
- [x] Share snapshots under this issue during the development process.
- [x] Mention this sub-issue in the parent development issue.

### Final Actions

When the related Pull Request is created and approved this issue will also be marked as complete and closed. 

### Deadline of the Issue

26.12.2022 - 23.59

### Reviewer

Mehmet Gökay Yıldız

### Deadline for the Review

26.12.2022 - 23.59

### PR DESCRIPTION
**Pull request by Koraytkn**
## Short Description

This is a revision PR detailed explanation has been provided via related [issue](https://github.com/bounswe/bounswe2022group2/issues/856)

------

## What Does This PR Include?

1. Profile page and components inside modification.
2. CSS file additions and revisions.

------

Closes #856

### CODE REVIEW

**Comment by gokayyildiz** [comment]
Ekran Resmi 2022-12-25 20 38 39

**Comment by gokayyildiz** [comment]
Also, when I clicked to the Painting learning space it does not direct me to the related ls page

**Comment by Koraytkn** [comment]
I am currently considering this review.

**Review by gokayyildiz — APPROVED** [review]
Thank you for the work now we can merge and after that we can open a pr to merge with dev-frontend

**Pull request merged**
