### PR TITLE
Mobile: Multi-Language Support - Settings

### LINKED ISSUE #761: Mobile: Multi-language Support and Settings
### Issue Description

I created a settings screen in the app with issue #758. The settings screen has a language section to allow users to select their native language. Our app was only supporting the English language previously. However, since our app should be a multicultural app that is used across the world, we thought to support various languages so that everyone can use our app easily. So, with this issue, I will implement the language section of the settings part. I will modify the language options enum, and language provider to allow dynamic setting of the language in the app.

Note: Translation of language JSON files and texts is not under the responsibility of this issue, it will be done separately.

### Step Details

Steps that will be performed:
- [x] Support the following languages in the app:
 * English
 * Turkish
 * Korean
 * Japanese
 * French
 * Spanish
 * German
 * Arabic
 * Mongolian
- [x] Add sample language JSON files for all supported languages
- [x] Implement selected language text under the language section in the settings screen
- [x] Implement a generic custom popup menu button
- [x] Add new supported languages list 
- [x] Implement get and set language methods (from/to the local storage)
- [x] Create helper methods for language names and icons
- [x] Add language flags and integrate them into the popup button
- [x] Add a listen-mechanism for the selected app language and update the app accordingly.

### Final Actions

I will test the implementation and widgets created on my real phone. If everything works, I will open a pull request. If the pull request is approved by at least one teammate, I will merge it and close the issue.

### Deadline of the Issue

21.12.2022 - Wednesday [23.59]

### Reviewer

Ezgi Aysel Batı

### Deadline for the Review

22.12.2022 - Thursday [23.59]

### PR DESCRIPTION
**Pull request by bahricanyesil**
## Short Description

With this PR, multi-language support will be added to the app with the pre-defined supported languages:
 * English
 * Turkish
 * Korean
 * Japanese
 * French
 * Spanish
 * German
 * Arabic
 * Mongolian
The corresponding language section in the settings screen will be implemented. Users will be able to select one of the languages mentioned above and the app will adjust its language/locale accordingly.

Note: Translation of language JSON files and texts is not under the responsibility of this PR, it will be done separately.

------

## What Does This PR Include?

1. Add sample language JSON files for all supported languages
2. Implement selected language text under the language section in the settings screen
3. Implement a generic custom popup menu button
4. Add new supported languages list 
5. Implement get and set language methods (from/to the local storage)
6. Create helper methods for language names and icons
7. Add language flags and integrate them into the popup button
8. Add a listen mechanism for the selected app language and update the app accordingly.

------

Closes #761

### CODE REVIEW

**Comment by bahricanyesil** [comment]
Here's a full-demonstrating video. It selects all languages one by one. It also demonstrates what happens when the app is restarted. The language selection of the user is stored and fetched accordingly. It also updates the app layout when the Arabic language is selected.

https://user-images.githubusercontent.com/60237280/208289520-f985c796-8e5a-43ba-b584-4536a4aa70f3.mp4

**Comment by bahricanyesil** [comment]
Here are the supported languages, they are added to our locales with corresponding language and country codes:

Screen Shot 2022-12-18 at 11 47 05

**Comment by bahricanyesil** [comment]
Here's a screenshot from the app that shows the language section under the settings screen:
(Note: Language texts will be updated later on by someone else on the team. Currently, just some texts are translated for demonstration purposes: "Settings"/"Made with..."/"Selected Language" 

Screen Shot 2022-12-18 at 11 48 33

**Comment by bahricanyesil** [comment]
Here's a screenshot from the app that shows the popup opened when a user tries to select another language:

Screen Shot 2022-12-18 at 11 49 47

**Review by egemenatikk — APPROVED** [review]

**Review by onurkomurcu — APPROVED** [review]
Great work, @bahricanyesil !

**Pull request merged**
