### PR TITLE
Verify email endpoint

### PR DESCRIPTION
**Pull request by codingAku**
Endpoint created. Users who are verified can very email again, for password renewing purposes. Includes sign-up endpoint.
Postman result:
verify

### CODE REVIEW

**Comment by mbatuhancelik** [comment]
First of all, we decided to merge to dev before user tests. This branch is way too ahead of master! 

Secondly, I dont get why we are resetting the jwt for each failed attempt. If we will reset the verification code, each code shall be sent to user via email.

Finally, it would be beneficial to return more detailed than "Wrong code" since they will be directly shown to the end user.

**Comment by codingAku** [comment]
Hello, after discussions this PR is complete

**Comment by mbatuhancelik** [comment]
yep, this looks good to me but you should still merge to dev.

**Comment by hasancan-code** [comment]
I was able to run this endpoint on my local, and it's complete. It can be merged now.

**Pull request merged**
