### PR TITLE
Create base folder structure, readme, gitignore and analysis options files

### LINKED ISSUE #332: Mobile: Initialization of the Project
### Issue Description

We will start to code our Online Learning Platform app in the upcoming days. I am a part of the mobile team as a result of our group split within the team. We will use Flutter while coding the Android app. This is the first issue about the mobile side of our project and I will define the initialization steps that should be performed under this issue before starting to code implementation of the project.

### Step Details

Steps that will be performed:
- [x] Create the "mobile" folder
- [x] Create a base project using the Flutter create command
- [x] Create the corresponding .gitignore file for Flutter
- [x] Create a Readme file
- [x] Create the base folder structure - Core/Features/Product
- [x] Create a pull request
- [x] Assign 2 reviewers (1 from the team and 1 from our TAs) for each pull request
- [x] Link related issues (e.g. this issue) in the pull request titles/descriptions

### Final Actions

After all of the items mentioned above are done, the reviewer will be reviewing the results of each section and provide final comments.

The mentioned steps will be also performed in the linked pull request and a review process will be there too.

### Deadline of the Issue

16.10.2022 - Sunday - 23:59

### Reviewer

Ezgi Aysel Batı - @ezgy 

### Deadline for the Review

17.10.2022 - Monday - 23:59

### PR DESCRIPTION
**Pull request by bahricanyesil**
We will start to code our Online Learning Platform app in the upcoming days. Therefore, I performed the initialization steps before starting to code the implementation of the project. I created the base setup for development. The following actions were taken with this PR:
- [x] Create the "mobile" folder
- [x] Create a base project using the Flutter create command
- [x] Create the corresponding .gitignore file for Flutter
- [x] Create a Readme file
- [x] Create the base folder structure - Core/Features/Product

Closes #332

### CODE REVIEW

**Comment by ezgy** [comment]
since we will be working with android only, is it possible to avoid the /ios folder completely? [Here ](https://stackoverflow.com/questions/67727537/how-can-i-delete-ios-folder-in-flutter-project) it says it is fine to just remove the folder.  I know this is the default initialization but having only the files we actually need will make it easier to work with and less confusing for beginners.

**Comment by bahricanyesil** [comment]
You're right. Actually, in the default initialization, "macos", "windows", "linux", and "web" folders are also created and I deleted them since they are unnecessary. However, I forgot to delete the ios folder. I will delete it and then the PR will be ready to merge.

**Comment by bahricanyesil** [comment]
I deleted the IOS folder, it's ready for merging @ezgy.

**Review by egemenatikk — APPROVED** [review]
Thank you for initializing the mobile part of our project @bahricanyesil .

**Pull request merged**
