### PR TITLE
Test cases for Login Page has been implemented and tested.

### PR DESCRIPTION
**Pull request by Koraytkn**
Among the unit test cases the one which is testing the case that the provided e-mail in the form is correct and registered but the password is wrong is using a temporary registered e-mail for now.

### CODE REVIEW

**Comment by gokayyildiz** [comment]
you can update the LoginForm.js to overcome some warnings 
> change class as className for 4 occurrences
> delete activeClassName related things

**Comment by Koraytkn** [comment]
@gokayyildiz could you check npm test with this branch right now, I have updated the login form page thanks to your previous feedback

**Comment by gokayyildiz** [comment]
Also, we can delete last 2 tests since it may be regarded as integration test since we expect an answer from another service and rely on the output of this service while conducting this unit tests

**Comment by Koraytkn** [comment]
You have right, but in order to see if the login page displays the right warning for the mistyped user information cases I think keeping them would be beneficial.

**Comment by Koraytkn** [comment]
@gokayyildiz I have removed the integration tests from the unit test file, thanks for the warnings and contributions.

**Review by gokayyildiz — APPROVED** [review]
Nicely done, thank you for your effort.

**Pull request merged**
