### PR TITLE
Mobile: Implementing Settings Screen

### LINKED ISSUE #758: Mobile: Implementing Settings Screen
### Issue Description

Almost all applications have a settings screen to enable users to set some preferences related to the app and also inform them. I will implement the settings screen of our application. The settings screen will be consisting of basic information about our app, our social media/contact accounts, and developer information (our team).

### Step Details

Steps that will be performed:
- [x] Create a settings view model
- [x] Add view model to the provider list
- [x] Create the settings screen
- [x] Add settings screen to the navigation router
- [x] Create a "Basic Info" component and add information about the app
- [x] Create a "Social Media/Contact Accounts" section
- [x] Add navigation to the settings screen from the settings icon in the profile screen

### Final Actions

I will test the implementation and widgets created on my real phone. If everything works, I will open a pull request. If the pull request is approved by at least one teammate, I will merge it and close the issue.

### Deadline of the Issue

21.12.2022 - Wednesday [23.59]

### Reviewer

Egemen Atik

### Deadline for the Review

22.12.2022 - Thursday [23.59]

### PR DESCRIPTION
**Pull request by bahricanyesil**
## Short Description

This PR creates a settings screen in our app and implements its navigation logic from the profile screen. The settings screen will include information about the app and additionally the social accounts with their links. Theme and languages sections will be implemented with separate PRs with multi-language and multi-theme supports.

------

## What Does This PR Include?

1. Creating a base settings screen
2. Creating a base settings view model class
3. Creating settings constant texts
4. Creating a settings list
5. Creating "Made with <3 by Learnify Team" footer text
6. Integrating settings screen into the main navigation stack
7. Implementing settings app bar
8. Creating base settings item widget as an expandable widget
9. Implementing generic bullet widget
10. Implementing generic colored widget and logic
11. Implementing app info section in the settings screen
12. Creating required texts for app info descriptions
13. Implementing social accounts section in the settings screen

------

Closes #758

### CODE REVIEW

**Comment by bahricanyesil** [comment]
## Update

I've implemented the settings with a general view of all sections' titles, subtitles, and icons. Here's a screenshot from the app:

Screen Shot 2022-12-18 at 00 56 03

**Comment by bahricanyesil** [comment]
## Update

I've implemented the app info section with 4 different description items. Here's a screenshot of the app info details:

Screen Shot 2022-12-18 at 00 58 17

**Comment by bahricanyesil** [comment]
## Update

I've implemented the social account info section with 3 different social account choices: Gmail, GitHub, and Learnify wiki page. All accounts have their corresponding links and can be reached by clicking on the icon. Here's a screenshot of the app info details:

Screen Shot 2022-12-18 at 01 04 25

**Comment by bahricanyesil** [comment]
## Update

Here's a final screenshot containing all the features implemented:

Screen Shot 2022-12-18 at 01 04 50

**Review by egemenatikk — APPROVED** [review]

**Pull request merged**
